import os

import pandas as pd
import numpy as np
import yaml
import pytest

from pybalance.genetic import GeneticMatcher
from pybalance.utils import MatchingData
from pybalance.datasets import load_toy_data


def test_noduplicates():
    # test that no patient is duplicated in candidate populations generated by generate_offspring()

    m = load_toy_data()
    matcher = GeneticMatcher(m, objective="beta")
    matcher._init_first_generation()
    stop = matcher._check_stopping_conditions()
    for generation in range(3):
        matcher._generate_offspring()
        for pop in matcher.candidate_populations:
            assert len(pop) == len(np.unique(pop))
