name: Docker Image CI

#on: [push, pull_request]
on:
  push:
    branches:
      - test
      - main
      - dev

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v3
      - name: Install Python 3.12 🐍
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Set up runner 📦
        run: pip3 install black==26.5.1
      - name: "Black: Code Formatting 👮🏽‍♀️"
        run: black --diff . && black -v --check .
      - name: install requirements
        run: pip install -r environments/requirements.txt
      - name: run tests
        run: PYTHONPATH=. pytest
