name: Deploy Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8' # install the python version needed
    - name: install deps
      run: |
        apt-get update && apt-get install -y wget gcc
        pip install -r environments/requirements.txt
        pip install -r environments/requirements_dev.txt
        wget https://github.com/jgm/pandoc/releases/download/2.17.1/pandoc-2.17.1-linux-amd64.tar.gz
        tar xzvf pandoc-2.17.1-linux-amd64.tar.gz
    - name: build docs
      run: |
        PYTHONPATH=. PATH=${PATH}:./pandoc-2.17.1/bin/ sphinx-build -b html sphinx docs
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
